name       : libfido2
version    : 1.5.0
release    : 1
source     :
    - https://github.com/Yubico/libfido2/archive/1.5.0.tar.gz : 5990f923c9390fe1e6a00ba5d1d1f74030e7344b855e971d9fb7223e70ff3122
license    : BSD-2-Clause
component  : security.library
summary    : Library functionality for FIDO 2.0
description: |
    libfido2 provides library functionality and command-line tools to communicate with a FIDO device over USB, and to verify attestation and assertion signatures.
    libfido2 supports the FIDO U2F (CTAP 1) and FIDO 2.0 (CTAP 2) protocols.
builddeps  :
    - pkgconfig(libcbor)
patterns   :
    - devel:
        - /usr/share/man/man3
setup      : |
    # Remove building of static library and examples
    patch -p1 < $pkgfiles/0001-Remove-building-of-static-library-and-examples.patch

    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
