name       : libfido2
version    : 1.12.0
release    : 3
source     :
    - https://github.com/Yubico/libfido2/archive/refs/tags/1.12.0.tar.gz : 813d6d25116143d16d2e96791718a74825da16b774a8d093d96f06ae1730d9c5
license    : BSD-2-Clause
component  : security.library
summary    : Library functionality for FIDO 2.0
description: |
    libfido2 provides library functionality and command-line tools to communicate with a FIDO device over USB, and to verify attestation and assertion signatures.
    libfido2 supports the FIDO U2F (CTAP 1) and FIDO 2.0 (CTAP 2) protocols.
builddeps  :
    - pkgconfig(libcbor)
    - pkgconfig(libpcsclite)
patterns   :
    - devel:
        - /usr/share/man/man3
setup      : |
    %cmake_ninja -DBUILD_STATIC_LIBS=OFF -DBUILD_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
